[package]
name = "geometry-rs"
version = "0.1.2"
edition = "2021"
license-file = "LICENSE"
description = "geometry utils"
homepage = "http://github.com/ringsaturn/geometry-rs"
documentation = "https://docs.rs/geometry-rs/latest/geometry_rs/"
repository = "http://github.com/ringsaturn/geometry-rs"
readme = "README.md"
keywords = ["geometry"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

float_next_after = "1.0.0"
